// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentFromLibrary(arg1) {
  return window['go']['main']['App']['AddAgentFromLibrary'](arg1);
}

export function AddExistingProject(arg1) {
  return window['go']['main']['App']['AddExistingProject'](arg1);
}

export function ApplyWorkflowChanges(arg1) {
  return window['go']['main']['App']['ApplyWorkflowChanges'](arg1);
}

export function ArchiveAgentGroup(arg1) {
  return window['go']['main']['App']['ArchiveAgentGroup'](arg1);
}

export function BindProjectAgentGroup(arg1) {
  return window['go']['main']['App']['BindProjectAgentGroup'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckModel(arg1) {
  return window['go']['main']['App']['CheckModel'](arg1);
}

export function ChooseProjectFolder() {
  return window['go']['main']['App']['ChooseProjectFolder']();
}

export function CreateAgentGroup(arg1) {
  return window['go']['main']['App']['CreateAgentGroup'](arg1);
}

export function CreateAgentGroupFromTemplate(arg1) {
  return window['go']['main']['App']['CreateAgentGroupFromTemplate'](arg1);
}

export function CreateChat(arg1) {
  return window['go']['main']['App']['CreateChat'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteLifecycleStep(arg1) {
  return window['go']['main']['App']['DeleteLifecycleStep'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DuplicateAgentProfile(arg1) {
  return window['go']['main']['App']['DuplicateAgentProfile'](arg1);
}

export function GetAgentSoul(arg1) {
  return window['go']['main']['App']['GetAgentSoul'](arg1);
}

export function ListAgentGroupTemplates() {
  return window['go']['main']['App']['ListAgentGroupTemplates']();
}

export function ListAgentGroups() {
  return window['go']['main']['App']['ListAgentGroups']();
}

export function ListAgentLibrary() {
  return window['go']['main']['App']['ListAgentLibrary']();
}

export function ListAgentProfiles(arg1) {
  return window['go']['main']['App']['ListAgentProfiles'](arg1);
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListLifecycleDefinitions(arg1) {
  return window['go']['main']['App']['ListLifecycleDefinitions'](arg1);
}

export function ListLifecycleSteps(arg1) {
  return window['go']['main']['App']['ListLifecycleSteps'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ReplaceAgentSoulFromLibrary(arg1) {
  return window['go']['main']['App']['ReplaceAgentSoulFromLibrary'](arg1);
}

export function RollbackWorkflowChanges(arg1) {
  return window['go']['main']['App']['RollbackWorkflowChanges'](arg1);
}

export function RunReview(arg1) {
  return window['go']['main']['App']['RunReview'](arg1);
}

export function RunTestCommand(arg1) {
  return window['go']['main']['App']['RunTestCommand'](arg1);
}

export function SaveAgentProfile(arg1) {
  return window['go']['main']['App']['SaveAgentProfile'](arg1);
}

export function SaveAgentSoul(arg1) {
  return window['go']['main']['App']['SaveAgentSoul'](arg1);
}

export function SaveLifecycleDefinition(arg1) {
  return window['go']['main']['App']['SaveLifecycleDefinition'](arg1);
}

export function SaveLifecycleStep(arg1) {
  return window['go']['main']['App']['SaveLifecycleStep'](arg1);
}

export function SaveModelConfig(arg1) {
  return window['go']['main']['App']['SaveModelConfig'](arg1);
}

export function SaveWebSettings(arg1) {
  return window['go']['main']['App']['SaveWebSettings'](arg1);
}

export function SelectChat(arg1) {
  return window['go']['main']['App']['SelectChat'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function SetAgentProfileEnabled(arg1) {
  return window['go']['main']['App']['SetAgentProfileEnabled'](arg1);
}

export function SubmitClarification(arg1) {
  return window['go']['main']['App']['SubmitClarification'](arg1);
}

export function UpdateAgentGroup(arg1) {
  return window['go']['main']['App']['UpdateAgentGroup'](arg1);
}

export function UpdateChat(arg1) {
  return window['go']['main']['App']['UpdateChat'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
