// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExistingProject(arg1) {
  return window['go']['main']['App']['AddExistingProject'](arg1);
}

export function ApplyWorkflowChanges(arg1) {
  return window['go']['main']['App']['ApplyWorkflowChanges'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CheckModel(arg1) {
  return window['go']['main']['App']['CheckModel'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function RunReview(arg1) {
  return window['go']['main']['App']['RunReview'](arg1);
}

export function RunTestCommand(arg1) {
  return window['go']['main']['App']['RunTestCommand'](arg1);
}

export function SaveModelConfig(arg1) {
  return window['go']['main']['App']['SaveModelConfig'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetActiveModel(arg1) {
  return window['go']['main']['App']['SetActiveModel'](arg1);
}

export function SubmitClarification(arg1) {
  return window['go']['main']['App']['SubmitClarification'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
